Raspython3
brain-hackers/cpython-wince pull request #1
Opened 2024-01-14 23:21 UTC by RasPython3

This PR reverts back the dropped Windows CE port of CPython and adds modifications to build it with CeGCC.

# Origin of patches
- https://github.com/python/cpython/commit/10108a7b9affa61719a1dc1863edb2bdb3402fd1

- https://sourceforge.net/projects/pythonce/files/pythonce/Python-2.5-20061219/PythonCE-2.5-20061219-source.zip/download

- https://sourceforge.net/projects/pythonce/files/pythonce/Python-2.5-20061219/PythonCE-2.5-20061219-patch.zip/download

2024-01-17 07:31 UTC, puhitaku requested changes
背景を聞きたい箇所、改善案、ただの感想、というふうにいくつかコメントしました。

Makefile にまとめた方がいいかも、の件は修正面倒だと思うので後でいいです。ただ、`ce_*.sh` は全体的に実験用便利スクリプト的な要素も見られたので、ロギングや distclean などのビルド以外の要素については、これらのスクリプトを呼ぶ人に一任する仕様に書き換えたほうがいいかなと思いました。

2024-01-17 07:31 UTC, puhitaku commented on Modules/Setup
何が起きてるのかわかってないけどこのファイルの diff が何を指しているのかわかると嬉しいです

2024-01-17 07:31 UTC, puhitaku commented on Modules/_tkinter.c
> +#undef finally /* Needed for Windows CE */
これは味わい深い（ただの感想）

2024-01-17 07:31 UTC, puhitaku commented on Modules/getpath.c
> +    return _PyStatus_ERR("you cant maybe in wince.");
改善案:
```suggestion
    return _PyStatus_ERR("Readlink is not available.");
```

2024-01-17 07:31 UTC, puhitaku commented on Modules/pwdmodule.c
module の定義も全部 `#ifndef` で消えてしまうので import がぶっ壊れないかが心配

2024-01-17 07:31 UTC, puhitaku commented on Modules/pyconfig.h
> +/* Windows CE does not support environment variables */
そうだったんだ（ただの感想）

2024-01-17 07:31 UTC, puhitaku commented on README-WINCE-3.rst
> +./ce_build.sh && ./ce_pack.sh
多分 Tcl/Tk のライブラリの用意も必要かなーと思いました

2024-01-17 07:31 UTC, puhitaku commented on WinCE/terminal.c
インデントが揃ってない（clang-format 使いたいのでこれは @puhitaku が一度対応します）
他に手で書いてるコードって何がありますか？

2024-01-17 07:31 UTC, puhitaku commented on ce_build.sh
> +export HOST_ARCH=arm-none-linux-gnu && \
export 末尾の `&& \` は不要じゃないかなーと思いましたが意図を教えてもらってもいいですか？

2024-01-17 07:31 UTC, puhitaku commented on ce_build.sh
> +
configure が実行されたことのない状態で `make distclean` すると失敗するので不要

2024-01-17 07:31 UTC, puhitaku commented on ce_build.sh
> +
ビルドログを残すなら ce_build.sh 全部の出力を残したいはずで、`set -x` によってコマンド実行ログを残したいといった場合も考えると、各コマンドを tee するよりは ce_build.sh を呼ぶ側で tee した方がよいに一票

あと、空ファイルを作る場合は `touch make.log` のがベターです

2024-01-17 07:31 UTC, puhitaku commented on ce_build.sh
> +build_tkinter='yes' # set 'no' or '' if you do not need tkinter being built.
[CI のログ](https://github.com/brain-hackers/cpython-wince/actions/runs/7551556012/job/20558959976#step:7:106472)を見る限り `_tkinter` がビルドされてないっぽいので修正が必要か否か気になってます

2024-01-17 07:31 UTC, puhitaku commented on ce_build.sh
> +ac_cv_enable_implicit_function_declaration_error=no \
Implicit function declaration は通常放っておくには危険な warning ですがあえて無視している背景はなんですか？

2024-01-17 07:31 UTC, puhitaku commented on ce_build.sh
> +echo "#endif /* !Py_CONFIG_H */" >> PC/pyconfig.h
`pyconfig.*` は全部バージョン管理されてますがあえてここで動的にいじってる背景を教えてもらってもいいですか？

2024-01-17 07:31 UTC, puhitaku commented on ce_build.sh
build, clean, mkpyc, pack は Makefile にまとめるとそれらしくなって良いなと思いました
`Makefile` というファイル名だとぶつかるので、`Makefile_ce` とか適当な名前にして `make -f Makefile_ce build` とか呼ぶ感じで

2024-01-17 07:31 UTC, puhitaku commented on ce_clean.sh
Shebang をつけてください

```
#!/bin/bash
```

2024-01-17 07:31 UTC, puhitaku commented on ce_clean.sh
> +rm make.log
ファイルがない場合にエラー終了するので `rm -rf` でまとめてください

```suggestion
rm -rf pyconfig.tmp pyconfig.pre.tmp zip.list wince_build make.log
```

2024-01-17 07:31 UTC, puhitaku commented on ce_mkpyc.py
> +    if py.endswith(".py") and not py.startswith(base_path + "test/") and not py.startswith(base_path + "lib2to3/"):
ここの `test/` と `lib2to3/` に対する not はどういう意図がありますか？現在の実装だと、`test/` と `lib2to3/` は compile されずに後段の `elif` に引っかかって py のままコピーされます。もしそもそもコピーせずに無視したいという意図であれば修正が必要です。

2024-01-17 07:31 UTC, puhitaku commented on ce_pack.sh
1. Shebang を付けてください
2. 本筋とは関係ないものの、standard library を zip で固めた場合と固めない場合でのメモリ使用量とスタートアップ時間の差は計測しても良さそうだなと思いました

2024-01-17 07:31 UTC, puhitaku commented on ce_pack.sh
> +#cp tk84.dll tcl84.dll celib.dll wince_build/
コピーしなくて大丈夫です？

2024-01-17 07:31 UTC, puhitaku commented on configure
> +	  ;;
インデント絡みで不要な diff がガッツリ入っているのでもとに戻したいところ

2024-01-17 07:31 UTC, puhitaku commented on configure
> +      ;;
インデント絡みで不要な diff がガッツリ入っているのでもとに戻したいところ

2024-01-17 07:31 UTC, puhitaku commented on configure.ac
> +      ;;
インデント絡みで不要な diff がガッツリ入っているのでもとに戻したいところ

2024-01-17 07:31 UTC, puhitaku commented on configure.ac
> +	  ;;
インデント絡みで不要な diff がガッツリ入っているのでもとに戻したいところ

2024-01-17 07:31 UTC, puhitaku commented on setup.py
> +print(os.name)
デバッグ出力でしょうか？削除をお願いします

2024-01-17 07:31 UTC, puhitaku commented on setup.py
> +    print(sys.path)
デバッグ出力でしょうか？削除をお願いします

2024-01-17 07:31 UTC, puhitaku commented on setup.py
Standard library のうち現状使えない module は一覧にしてまとめてどこかに書いておくとユーザーには嬉しいかもしれないです

2024-01-17 07:31 UTC, puhitaku commented on Modules/_pickle.c
> +    ___UNICODE       = 'V',
これ味わい深い（ただの感想）

2024-01-17 08:36 UTC, RasPython3 commented on ce_build.sh
> +build_tkinter='yes' # set 'no' or '' if you do not need tkinter being built.
少しわかりにくいんですが、`_tkinter`は実際にはビルドされています。
環境変数で`_TCLTK_LIBS`や`_TCLTK_INC`が設定されずに`setup.py`が呼ばれるタイミングが一度だけあり、そのタイミングでビルドされていないと表示されているようです。
これの対処についてはどうしようか悩んでいます。

まだ試していませんが、ここでnoにしたら、`_tkinter`はビルドされないはずです。実際にビルドされていれば、生成される`wince_build`内に`_tkinter.pyd`があるはずです。

2024-01-17 08:39 UTC, RasPython3 commented on ce_build.sh
> +ac_cv_enable_implicit_function_declaration_error=no \
宣言の順番の問題か、多いんですよね...
あと、存在すると思われる一部の関数等で、cegccのヘッダで宣言されていないものもあるようです。
implicit function declarationが重大なものであることはわかった上で、そこまで手を回すと非常に時間がかかりそうだったので、一旦開発速度を優先してました。

2024-01-17 08:54 UTC, RasPython3 commented on ce_build.sh
> +echo "#endif /* !Py_CONFIG_H */" >> PC/pyconfig.h
本来Unix系のツールであるMakefileを利用するとなったときに、`PC/pyconfig.h`の中身が`pyconfig.h`とは違って、自動では変更されないことがわかって、一部のマクロを適用するためにこの様に処理しています。
最初は、`pyconfig.h`内のマクロの大半を適用するつもりでしたが、結局うまく行かず、`PY_BUILTIN_HASHLIB_HASHES`だけ適用しています。

88行目のコメントアウトがその痕跡ですね。この処理については、なんとか調整して動かしたいところなので、そのままにしてあります。

2024-01-17 08:55 UTC, RasPython3 commented on ce_build.sh
`Makefile`という名前以外でも`make`できることを知らなかった...
そうですね、そうするのが良さそうです。

2024-01-17 08:55 UTC, RasPython3 commented on ce_clean.sh
忘れてました。つけておきます。

2024-01-17 08:56 UTC, RasPython3 commented on ce_clean.sh
> +rm make.log
了解です。この`ce_clean.sh`はまだかなり適当なので、もう少しきちんと書き直したほうがいいかもしれないですね...

2024-01-17 08:59 UTC, RasPython3 commented on ce_mkpyc.py
> +    if py.endswith(".py") and not py.startswith(base_path + "test/") and not py.startswith(base_path + "lib2to3/"):
`test/`と`lib2to3/`は、コンパイル時にエラーが多発したため、そもそものコンパイルをしていません。
でも、`import`する分には、多少遅くなるかもしれませんが、importできるものもありますので、`.py`のままコピーしています。

2024-01-17 09:03 UTC, RasPython3 commented on ce_pack.sh
> +#cp tk84.dll tcl84.dll celib.dll wince_build/
`???._pth`の`???`の部分は、`libpython3.10.dll`または`libpython3.10d.dll`の、拡張子を除いた部分と一致する必要があります。この`mv`の目的は名称変更なので、問題ありません。

2024-01-17 09:04 UTC, RasPython3 commented on setup.py
> +print(os.name)
了解です。消しておきます。

2024-01-17 09:04 UTC, RasPython3 commented on setup.py
> +    print(sys.path)
了解です。消しておきます。

2024-01-17 09:05 UTC, RasPython3 commented on Modules/_pickle.c
> +    ___UNICODE       = 'V',
`UNICODE`も`_UNICODE`も`__UNICODE`もすでに使われてた...

2024-01-17 09:08 UTC, RasPython3 commented on Modules/Setup
うーんと、tkinter周り以外は、ここで書かないとうまくビルドされなかったためです。
本来の処理の流れがいまいち読めていないので、改善点ではあります。
tkinterのところは、初めの方はここでどうにかしようと試行錯誤していましたが、`configure`に`_TCLTK_*`を与えれば解決するとわかり、コメントアウトしました。その名残です。
その部分は、元の`Setup`のものに戻したほうが良さそうですね。

2024-01-17 09:13 UTC, RasPython3 commented on Modules/getpath.c
> +    return _PyStatus_ERR("you cant maybe in wince.");
そっちのほうが良いですね。変更しておきます。

2024-01-17 09:15 UTC, RasPython3 commented on Modules/pwdmodule.c
うーん、これは確かPythonCEのときの変更なので、なんとも言えないですね...

2024-01-17 09:16 UTC, RasPython3 commented on README-WINCE-3.rst
> +./ce_build.sh && ./ce_pack.sh
かなり書きかけなのと、この後結構変更が入りそうなので、一旦放置しようかなと思いますが、どうでしょうか？

2024-01-17 09:18 UTC, RasPython3 commented on WinCE/terminal.c
`WinCE/terminal.h`と、ほとんど`Modules/_io/winconsoleio.c`そのままな`Modules/_io/winceconsoleio.c`ぐらいだと思いますが...
忘れてたらすみません。

2024-01-17 09:18 UTC, RasPython3 commented on ce_build.sh
> +export HOST_ARCH=arm-none-linux-gnu && \
cpythonのクロスコンパイルのやり方を調べているときに、この書き方をしているサイトが有り、それを真似ただけですね。消しても問題ないと思います。

2024-01-17 09:19 UTC, RasPython3 commented on ce_pack.sh
`#!/bin/bash`つけておきます。
zipで固めない場合...なるほど。面白そうですね。
固める処理は`ce_pack.sh`の仕事なので、オプションを付けて試せるようにしておきます。

2024-01-17 09:23 UTC, RasPython3 commented on ce_pack.sh
> +#cp tk84.dll tcl84.dll celib.dll wince_build/
これコメントアウトされた30行目のことか()
コピー...しといたほうがいいですねコレ。

2024-01-17 09:29 UTC, RasPython3 commented on ce_build.sh
> +
空ファイルのところだけ修正して、
他はce版のMakefileを作る際にまとめて処理します。

2024-01-17 09:30 UTC, RasPython3 commented on ce_build.sh
> +
了解です。消しておきます。

2024-01-17 11:13 UTC, RasPython3 commented on ce_pack.sh
(ce_pack.shは一旦あとにしておきます)

2024-01-17 11:16 UTC, RasPython3 commented on Modules/Setup
(一旦そのままにしておきます)

2024-01-17 11:28 UTC, RasPython3 commented on Modules/pwdmodule.c
調べたところ、WindowsのPythonには含まれないファイルのようなので、問題はなさそうです。

2024-01-17 11:29 UTC, RasPython3 commented on Modules/pyconfig.h
> +/* Windows CE does not support environment variables */
GetVersionの値があってるか、今考えるとわからないですね...
PythonCEに書かれていたとおりに書いたので、CE6.0のものじゃないかも...?

2024-01-17 11:31 UTC, RasPython3 commented on ce_build.sh
> +export HOST_ARCH=arm-none-linux-gnu && \
消しておきました。

2024-01-17 22:11 UTC, puhitaku commented on Modules/Setup
tkinter 以外の部分、了解です。
tkinter 関連のコメントアウトされてる箇所は、正解かどうかわからない結果のコメントアウトであれば元に戻した方が良さそうです。

Tcl/Tk のビルド時の認識についての根本解決は別の機会でいいとして、以下考察:

現在 Tcl/Tk を認識させている `_TCLTK_*` は名前からして internal な雰囲気があります。zlib, Tcl/Tk, readline といった依存はビルド時に自動で見つけさせるのが一般的なルートであることを考えると、Tcl/Tk の header や dll を pkg-config を介して見つけさせることになるのが正解ではないかなと推理します。

Debian でのビルドを例に調べると、[pyenv で Python を入れるときに必要なパッケージ一覧](https://github.com/pyenv/pyenv/wiki#suggested-build-environment)には `tk-dev` があり、この依存とそのファイル一覧を調べると tcl と tk の静的・動的ライブラリファイルと pkgconfig ファイル (`.pc`) があります。

```sh
$ apt show tk-dev
Package: tk-dev
... 略 ...
Depends: tk8.6-dev (>= 8.6.9-2), tk, tcl-dev
# ここで、tcl-dev も tk-dev と同様に実際には依存で tcl8.6-dev を指す

$ apt-file show tcl8.6-dev
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/compat/dirent.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/compat/dirent2.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/compat/dlfcn.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/compat/fake-rfc2553.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/compat/float.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/compat/stdlib.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/compat/string.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/compat/unistd.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/regcustom.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/regerrs.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/regex.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/regguts.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tcl.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclCompile.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclDecls.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclFileSystem.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclIO.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclInt.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclIntDecls.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclIntPlatDecls.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclOO.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclOODecls.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclOOInt.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclOOIntDecls.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclParse.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclPlatDecls.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclPort.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclRegexp.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclStringRep.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclStringTrim.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclTomMath.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclTomMathDecls.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tclTomMathInt.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/generic/tommath.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/libtommath/tommath.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/libtommath/tommath_class.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/libtommath/tommath_superclass.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/unix/tclUnixPort.h
tcl8.6-dev: /usr/include/tcl8.6/tcl-private/unix/tclUnixThrd.h
tcl8.6-dev: /usr/include/tcl8.6/tcl.h
tcl8.6-dev: /usr/include/tcl8.6/tclDecls.h
tcl8.6-dev: /usr/include/tcl8.6/tclOO.h
tcl8.6-dev: /usr/include/tcl8.6/tclOODecls.h
tcl8.6-dev: /usr/include/tcl8.6/tclPlatDecls.h
tcl8.6-dev: /usr/include/tcl8.6/tclTomMath.h
tcl8.6-dev: /usr/include/tcl8.6/tclTomMathDecls.h
tcl8.6-dev: /usr/lib/tcl8.6/tclConfig.sh
tcl8.6-dev: /usr/lib/tcl8.6/tclooConfig.sh
tcl8.6-dev: /usr/lib/x86_64-linux-gnu/libtcl8.6.a
tcl8.6-dev: /usr/lib/x86_64-linux-gnu/libtclstub8.6.a
tcl8.6-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/tcl8.6.pc
tcl8.6-dev: /usr/lib/x86_64-linux-gnu/tcl8.6/tclConfig.sh
tcl8.6-dev: /usr/lib/x86_64-linux-gnu/tcl8.6/tclooConfig.sh
tcl8.6-dev: /usr/share/aclocal/tcl8.6.m4
tcl8.6-dev: /usr/share/doc/tcl8.6-dev/README.TCL_INC
tcl8.6-dev: /usr/share/doc/tcl8.6-dev/changelog.Debian.gz
tcl8.6-dev: /usr/share/doc/tcl8.6-dev/changelog.gz
tcl8.6-dev: /usr/share/doc/tcl8.6-dev/copyright

$ apt-file show tk8.6-dev
tk8.6-dev: /usr/include/tcl8.6/tk-private/compat/stdlib.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/compat/unistd.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/default.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/ks_names.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tk.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tk3d.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkBusy.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkButton.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkCanvas.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkColor.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkDecls.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkEntry.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkFileFilter.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkFont.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkImgPhoto.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkInt.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkIntDecls.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkIntPlatDecls.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkIntXlibDecls.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkMenu.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkMenubutton.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkPlatDecls.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkPort.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkScale.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkScrollbar.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkSelect.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkText.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/tkUndo.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/ttk/ttkDecls.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/ttk/ttkManager.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/ttk/ttkTheme.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/ttk/ttkThemeInt.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/generic/ttk/ttkWidget.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/unix/tkUnixDefault.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/unix/tkUnixInt.h
tk8.6-dev: /usr/include/tcl8.6/tk-private/unix/tkUnixPort.h
tk8.6-dev: /usr/include/tcl8.6/tk.h
tk8.6-dev: /usr/include/tcl8.6/tkDecls.h
tk8.6-dev: /usr/include/tcl8.6/tkPlatDecls.h
tk8.6-dev: /usr/lib/tk8.6/tkConfig.sh
tk8.6-dev: /usr/lib/x86_64-linux-gnu/libtk8.6.a
tk8.6-dev: /usr/lib/x86_64-linux-gnu/libtkstub8.6.a
tk8.6-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/tk8.6.pc
tk8.6-dev: /usr/lib/x86_64-linux-gnu/tk8.6/tkConfig.sh
tk8.6-dev: /usr/share/doc/tk8.6-dev/changelog.Debian.gz
tk8.6-dev: /usr/share/doc/tk8.6-dev/changelog.gz
tk8.6-dev: /usr/share/doc/tk8.6-dev/copyright
```

ここで、 `.pc` ファイルは標準的な path に置いてあるので、CPython のビルド時には pkg-config がこれらの `.pc` ファイルを見つけて include path と library path が解決されます。もちろんこの path はカスタマイズができて、通常なら `PKG_CONFIG_PATH` を指定すれば好きな位置の `.pc` を認識させられます。

`.pc` ファイルは特定の書式で include path と library path とバージョンが書かれたただのテキストファイルなので、自分で書いてでっち上げることもできます。

2024-01-17 22:11 UTC, puhitaku commented on Modules/pyconfig.h
> +/* Windows CE does not support environment variables */
たしかにそうかも知れないですね笑

2024-01-17 22:23 UTC, puhitaku commented on README-WINCE-3.rst
> +./ce_build.sh && ./ce_pack.sh
OK です！

2024-01-17 22:23 UTC, puhitaku commented on ce_build.sh
> +build_tkinter='yes' # set 'no' or '' if you do not need tkinter being built.
おお、なるほど。ビルドの特殊さに起因してるログだったんですね。
`Modules/Setup` の方にブワーと書いちゃいましたがこれはまた後日解決で OK です。

2024-01-17 22:23 UTC, puhitaku commented on ce_build.sh
> +ac_cv_enable_implicit_function_declaration_error=no \
include の流れがちょっと特殊なのでそういう事も起きそうですね。説明ありがとうございます。

2024-01-17 22:23 UTC, puhitaku commented on ce_build.sh
> +echo "#endif /* !Py_CONFIG_H */" >> PC/pyconfig.h
わかりました！

2024-01-17 22:23 UTC, puhitaku commented on ce_build.sh
👍 
Makefile 統合はまた今度やりましょう

2024-01-17 22:23 UTC, puhitaku commented on ce_mkpyc.py
> +    if py.endswith(".py") and not py.startswith(base_path + "test/") and not py.startswith(base_path + "lib2to3/"):
背景理解しました。`test` も `lib2to3` も実アプリケーションで使うことがまずないので、むしろ完全に放っておいてもよさそうですね。

2024-01-17 22:23 UTC, puhitaku commented on ce_pack.sh
> +#cp tk84.dll tcl84.dll celib.dll wince_build/
> これコメントアウトされた30行目のことか

です！修正確認しました。

2024-01-17 22:23 UTC, puhitaku commented on setup.py
書き忘れてました、本件別の機会で OK です

2024-01-18 00:31 UTC, RasPython3 commented on Modules/Setup
誤りでした。正しくは`TCLTK_*`でした。`./configure --help`とすると、
  --with-tcltk-includes='-I...'
                          override search for Tcl and Tk include files
  --with-tcltk-libs='-L...'
                          override search for Tcl and Tk libs
これらを指定すると、Makefileで`TCLTK_*`が設定されて(`PC/WinCE/_tkinter`に代替ヘッダーが存在するためincludeをそこにする)、tkinterのビルドが走るようになるみたいです。
Setupは直しておきますね。

2024-01-18 00:31 UTC, RasPython3 commented on setup.py
了解です。

2024-01-18 00:34 UTC, RasPython3 commented on configure
> +      ;;
`configure.ac`から生成されるファイルなので、そちらで対応します。

2024-01-18 00:34 UTC, RasPython3 commented on configure
> +	  ;;
`configure.ac`から生成されるファイルなので、そちらで対応します。

2024-01-18 00:35 UTC, RasPython3 commented on configure.ac
> +      ;;
これvimの設定でタブ文字置き換えられてましたね...

2024-01-18 02:33 UTC, RasPython3 commented on configure.ac
> +	  ;;
多分直せました。

2024-01-18 02:34 UTC, RasPython3 commented on configure.ac
> +      ;;
多分直せました。

2024-01-18 02:34 UTC, RasPython3 commented on configure
> +	  ;;
多分直せました。

2024-01-18 02:38 UTC, RasPython3 commented on Modules/Setup
修正しました。

2024-01-22 08:35 UTC, puhitaku approved these changes
![f6232839-1a8b-4ca6-9c9b-86be1203014e](https://github.com/brain-hackers/cpython-wince/assets/2425178/8258e06b-c3e8-48f3-a415-7e93c152fa4d)

2024-01-22 09:47 UTC, puhitaku commented
CI 直しました
ビビった

2024-01-22 09:50 UTC, merged